version: '3.7'

services:
  shelby-mongo:
    image: mongo:4.0.19
    restart: always
    container_name: shelby-mongo
    ports:
      - 27017:27017

  shelby-eureka:
    image: shelby-eureka
    restart: always
    container_name: shelby-eureka
    ports:
      - 8761:8761

  shelby-api-gateway:
    image: shelby-api-gateway
    restart: always
    container_name: shelby-api-gateway
    ports:
      - 9080:9080
    environment:
      - SERVER_PORT=9080
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
    depends_on:
      - shelby-eureka

  shelby-refdata-1:
    image: shelby-refdata
    restart: always
    container_name: shelby-refdata-1
    ports:
      - 9091:9091
    environment:
      - SPRING_DATA_MONGODB_DATABASE=shelby-refdata
      - SPRING_DATA_MONGODB_HOST=shelby-mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SERVER_PORT=9091
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
    depends_on:
      - shelby-mongo
      - shelby-eureka

  shelby-refdata-2:
    image: shelby-refdata
    restart: always
    container_name: shelby-refdata-2
    ports:
      - 9092:9092
    environment:
      - SPRING_DATA_MONGODB_DATABASE=shelby-refdata
      - SPRING_DATA_MONGODB_HOST=shelby-mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SERVER_PORT=9092
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
    depends_on:
      - shelby-mongo
      - shelby-eureka

  shelby-ui:
    image: shelby-ui
    restart: always
    container_name: shelby-ui
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
    depends_on:
      - shelby-eureka