version: '3.7'

services:
  mongodb:
    image: mongo:4.0.19
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017

  shelby-eureka:
    image: shelby-eureka
    restart: always
    container_name: shelby-eureka
    ports:
      - 8761:8761

  shelby-api-gateway:
    image: shelby-api-gateway
    restart: always
    container_name: shelby-api-gateway
    ports:
      - 9080:9080
    environment:
      - SERVER_PORT=9080
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
      - ZUUL_ROUTES_SECURITY_PATH=/security/**
      - ZUUL_ROUTES_SECURITY_URL=http://shelby-SECURITY:9091
      - ZUUL_ROUTES_FX_PATH=/fx/**
      - ZUUL_ROUTES_FX_URL=http://shelby-fx:9092
    depends_on:
      - shelby-eureka

  shelby-security:
    image: shelby-security
    restart: always
    container_name: shelby-security
    ports:
      - 9091:9091
    environment:
      - SPRING_DATA_MONGODB_DATABASE=shelby-security
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SERVER_PORT=9091
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
    depends_on:
      - mongodb
      - shelby-eureka

  shelby-fx:
    image: shelby-fx
    restart: always
    container_name: shelby-fx
    ports:
      - 9092:9092
    environment:
      - SPRING_DATA_MONGODB_DATABASE=shelby-fx
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SERVER_PORT=9092
      - EUREKA_CLIENT_SERVICE-URL_DEFAULT-ZONE=http://shelby-eureka:8761/eureka
    depends_on:
      - mongodb
      - shelby-eureka